import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Image from "next/image";
import deleteIcon from "../public/delete.png"
import plus from "../public/plus.png"
import {useAppDispatch, useAppSelector} from "../redux/hooks";
import {addTodo, selectTodoData} from "../redux/slices/todo";
import {useRef} from "react";

export default function Home() {
    const refInput = useRef()
    const todoData = useAppSelector(selectTodoData)
    const dispatch = useAppDispatch();
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.wrapper}>
                <div className={styles.head}>Todo App</div>
                <div className={styles.inputMain}>
                    <input ref={refInput} type="text"  placeholder="Todo.." className={styles.input}/>
                    <div className={styles.AddBtn} onClick={() => dispatch(addTodo(refInput.current.value))}>
                        <Image
                            src={plus}
                            width={24}
                            height={24}
                        >
                        </Image>
                    </div>
                </div>
                {todoData.todos.map((todo) =>
                    <div className={styles.todo} key={todo}>
                        {todo}
                        <Image className={styles.image}
                               src={deleteIcon}
                               width={32}
                               height={32}
                        />
                    </div>)}
            </div>
        </div>
    )
}
