import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import React from "react";
import Image from "next/image";
import plus from "../public/plus.png"
import {useAppDispatch,} from "../redux/hooks";
import {addTodo,} from "../redux/slices/todo";
import {useRef} from "react";
import TodoList from "../components/TodoList";
import CompleteTodo from "../components/CompleteTodo";

export default function Home() {
    const refInput = useRef()
    const dispatch = useAppDispatch();
    const [isBrowser, setIsBrowser] = React.useState(false);

    React.useEffect(() => {
        setIsBrowser(process.browser);
    }, [])

    function addTodoApp() {
        const value = refInput.current.value
        if (value !== '') {
            dispatch(addTodo(value))
            refInput.current.value = ''
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Todo</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div  className={styles.menu}>
                <div className={styles.wrapper}>
                    <div className={styles.title}>В прогрессе</div>
                    <div className={styles.form}>
                        <input ref={refInput} type="text" placeholder="Todo.." className={styles.input}/>
                        <div className={styles.addbtn} onClick={addTodoApp}>
                            <Image src={plus} width={24} height={24}/>
                        </div>
                    </div>
                    {isBrowser ? <TodoList/> : null}
                </div>
                <CompleteTodo/>
            </div>
        </div>
    )
}

