import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Image from "next/image";
import plus from "../public/plus.png"
import {useAppDispatch, useAppSelector} from "../redux/hooks";
import {addTodo, removeTodo, selectTodoData} from "../redux/slices/todo";
import {useRef} from "react";
import deleteIcon from "../public/delete.png"
import {DragDropContext, Draggable, Droppable} from "react-beautiful-dnd";
import React from "react";
import TodoList from "../components/TodoList";

export default function Home() {
    const refInput = useRef()
    const dispatch = useAppDispatch();
    function addTodoApp() {
        const value = refInput.current.value
        if (value !== '') {
            dispatch(addTodo(value))
            refInput.current.value = ''
        }
    }

    const [isBrowser, setIsBrowser] = React.useState(false);

    React.useEffect(() => {
        setIsBrowser(process.browser);
    }, [])

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.wrapper}>
                <div className={styles.head}>Todo App</div>
                <div className={styles.inputMain}>
                    <input ref={refInput} type="text" placeholder="Todo.." className={styles.input}/>
                    <div className={styles.AddBtn} onClick={addTodoApp}>
                        <Image src={plus} width={24} height={24}/>
                    </div>
                </div>
                {isBrowser ? <TodoList/> : null}
            </div>
        </div>
    )
}

